# Theme settings
url: "https://blog.palcu.ro"
twitter_username: AlexPalcuie
github_username: palcu
author: Alex Palcuie
timezone: Europe/Bucharest

# SEO
title: "Alex Palcuie | Palcu's Blog"
description: "I write about my life filled with stuff related to programming computers."
google_site_verification: 1-bnMsg8ZPhhZ9zuL4v7412nngKzSpbJMxae_2TnRWg
twitter:
  username: AlexPalcuie
social:
  name: Alex Palcuie
  links:
    - https://twitter.com/alexpalcuie/
    - https://www.facebook.com/palcuiealex
    - https://www.linkedin.com/in/alexpalcuie
    - https://github.com/palcu
    - https://plus.google.com/+AlexPalcuie
facebook:
  app_id: 202914823068704
logo: '/assets/glider.png'
my_face: /assets/alex_palcuie.png


# For SEO reasons, this is the same structure as in Blogger
permalink: "/:year/:month/:title.html"

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
