# Site settings
title: Palcu's Blog
description: >
  Software engineer and geek student. I like algorithms, startups and guitars.
  I am a voracious reader.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://palcu.github.io" # the base hostname & protocol for your site
twitter_username: AlexPalcuie
github_username:  palcu

# Build settings
markdown: kramdown
