# Site settings
title: Palcu's Blog
email: alex dot palcuie at gmail dot com
description: >
  Strings of code and thoughts.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://palcu.github.io" # the base hostname & protocol for your site
twitter_username: AlexPalcuie
github_username:  palcu

# Build settings
markdown: kramdown
