name: Alex Palcuie's Blog
description: "I solve meaningful problems using software and help other people."

url: "http://blog.palcu.ro"
twitter_username: AlexPalcuie
github_username: palcu

# For SEO reasons, this is the same structure as in Blogger
permalink: "/:year/:month/:title.html"

# Pagination
paginate: 7
paginate_path: "/blog/page:num/"

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
