# Site settings
title: Palcu's Blog
description: >
  Self-taught hacker. I like to code, break things and help other people.
  I write and teach Python and I build user interfaces on the web in Javascript with React.
url: "http://blog.palcu.ro"
twitter_username: AlexPalcuie
github_username:  palcu

# For SEO reasons, this is the same structure as in Blogger
permalink: "/:year/:month/:title.html"

# Build settings
markdown: kramdown

# Pagination
paginate: 7
paginate_path: "/blog/page:num/"

# Github pages feed
gems:
  - jekyll-feed
