# Theme settings
name: Alex Palcuie's Blog
url: "http://blog.palcu.ro"
twitter_username: AlexPalcuie
github_username: palcu

# SEO
title: Alex Palcuie's Blog
description: "I solve meaningful problems using software and help other people."
google_site_verification: 1-bnMsg8ZPhhZ9zuL4v7412nngKzSpbJMxae_2TnRWg
twitter:
  username: AlexPalcuie
social:
  name: Alex Palcuie
  links:
    - https://twitter.com/alexpalcuie/
    - https://www.facebook.com/palcuiealex
    - https://www.linkedin.com/in/alexpalcuie
    - https://github.com/palcu
facebook:
  app_id: 202914823068704

# For SEO reasons, this is the same structure as in Blogger
permalink: "/:year/:month/:title.html"

# Pagination
paginate: 7
paginate_path: "/blog/page:num/"

gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
