# Site settings
name: Palcu's Blog
title: Palcu's Blog
description: "I love solving meaningful problems using software and helping other people."
url: "http://blog.palcu.ro"
twitter_username: AlexPalcuie
github_username:  palcu

# For SEO reasons, this is the same structure as in Blogger
permalink: "/:year/:month/:title.html"

# Pagination
paginate: 7
paginate_path: "/blog/page:num/"

# Github pages feed
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
