# Theme settings
name: "Alex Palcuie | Palcu's Blog"
url: "https://blog.palcu.ro"
twitter_username: AlexPalcuie
github_username: palcu

# SEO
title: "Alex Palcuie | Palcu's Blog"
description: "I solve meaningful problems using software and help other people. I write about programming, computer science, open source and other things."
google_site_verification: 1-bnMsg8ZPhhZ9zuL4v7412nngKzSpbJMxae_2TnRWg
twitter:
  username: AlexPalcuie
social:
  name: Alex Palcuie
  links:
    - https://twitter.com/alexpalcuie/
    - https://www.facebook.com/palcuiealex
    - https://www.linkedin.com/in/alexpalcuie
    - https://github.com/palcu
    - https://plus.google.com/+AlexPalcuie
facebook:
  app_id: 202914823068704

# For SEO reasons, this is the same structure as in Blogger
permalink: "/:year/:month/:title.html"

sass:
  style: compressed

gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-paginate
  - jemoji
  - jekyll-sitemap
