#!/bin/bash

rvm use ruby-2.4.1
rvm gemset use palcu.github.com
# http://stackoverflow.com/questions/25176674/run-process-when-string-in-stdout-is-matched/25177206#25177206
(bundle exec jekyll serve) | while read line; do
    [[ $line =~ "Server running" ]] && open http://localhost:4000
    echo $line
done
